### ISSUE TITLE
browser.storage.sync out of control

### ISSUE THREAD

**Issue by schwabeltier** [sweitzel/Biet-O-Matic-BE#14]
Moin,
bei mir sind 3111.88% des browser.storage.sync belegt und die Anwendung bietet nicht mehr richtig, startet auch nicht mehr, 
und die gelöschten Artikel aus der Liste erscheinen beim erneuten Aufruf wieder, wurden also nicht gelöscht.
Ich habe 83 Seiten mit Artikeln voll. Die BE ist leider sehr langsam und verzögert.
Die Buttons funktionieren nur nach zum Teil Minuten nach dem Klick oder reagieren garnicht oder ohne Auswirkung auf die Liste der Artikel.
Z.B. Das Löschen aller beendeten Angebote bewirkt, dass die Meldung oben kommt, dass 2045 Artikel gelöscht wurden. Allerdings ändert sich auch nach Stunden nichts daran, dass die Artikel dennoch in der Liste auffindbar sind, als wäre nichts gewesen. Was wäre mit einem Storage -Bereiniger?
Riecht nach ungehandelter HeapSpaceException oder so.
Wenn das umgesetzt wird, gibts es wieder eine Spende.

**Comment by sweitzel** [comment]
Ich nehme an hierbei handelt es sich um das bekannte Problem mit Firefox 79. 

Abhilfe hilft nur das komplette löschen des Speichers der BE Erweiterung:
- Aufrufen der BE Übersichtsseite
- drücken der F12 Taste zur Aktivierung der Konsole
- Eingabe von:
```
browser.storage.sync.clear();
```

Danach kann dieses Problem nicht mehr auftreten. Firefox forciert nun eine Quota - es können nun allerdings bedeutend weniger Artikel in BE gespeichert werden (bei Chrome genauso).


Hintergründe:
- https://www.bid-o-matic.org/forum/viewtopic.php?t=4158
- https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/

**Comment by schwabeltier** [comment]
Hi,
also vielleicht wäre eine Möglichkeit alle Artikel, nachdem sie beendet wurden einfach aus dem BE-Storage zu löschen?
Vielleicht könnte man das einfach als einstellbare Option auswählbar machen.

**Comment by sweitzel** [comment]
Eine Aktion zum Aufräumen von Artikeln ist ja bereits eingebaut und kann vom Benutzer ausgeführt werden. Einen Automatismus dafür halte ich für unnötig, denn letztendlich verschiebt es das Problem nur. 

Ich überlege aber einen "lokalen Modus" einzubauen. Bei dem kann man dann deutlich mehr Artikel speichern da die Daten dann lokal gespeichert werden (aktuell wird ja immer im auf 100kb begrenzen browser.sync storage gespeichert). Generell bin ich aber der Meinung das die BE zum Bieten und nicht zum verwalten / Übersicht über "interessante" Artikel sein sollte - manche Nutzer sehen das aber freilich anders. 
Außerdem sollte die Situation, das der Speicher voll ist deutlicher angezeigt werden.

**Comment by schwabeltier** [comment]
Ich stimme Dir in allen Punkten zu. Den lokalen Speicher halte ich für eine gute Idee.

**Comment by sweitzel** [comment]
Version 0.5.0 behebt das Problem durch Einführung des "Lokalen Modus",
