### ISSUE TITLE
Bids are not working - timing?????

### ISSUE THREAD

**Issue by dvanco** [sweitzel/Biet-O-Matic-BE#15]
Would really like someone to comment on why I'm seeing these failures. I've tried to ask via the Chrome page but I've gotten no replies 
![image](https://user-images.githubusercontent.com/13891989/93290260-56272e80-f7ae-11ea-8f28-baa75fb61cae.png)

Everything looks fine - it's like the tool just didn't bid.

I REALLY think the bid time is too aggressive - I want to change it to 7 seconds - surely there's something in the local plugin directory I can edit to make this happen

**Comment by sweitzel** [comment]
Can you please confirm how often the bidding process fails? Or was that the first time? How many successful bids did you have before?

I already know that the current implementation has its limitations. That's why I currently rewrite the bidding process completely to make it simpler and more robust. Also the bidding time can be adjusted by the user in the next version.

It will still take me a while to release the new version though (hopefully in October).

**Comment by dvanco** [comment]
> Can you please confirm how often the bidding process fails?

It is sporadic - a couple times a week, maybe 1 out of 30 to 40 bids. I have not kept an accurate count, but it does reoccur.
As you can see these 2 were very close together.

> Or was that the first time?

The first time was August 28th.
https://imgur.com/a/fIB0HO8

> How many successful bids did you have before?

As I said above, I have had MANY successful bids (earlier in the same day in this case) - it is sporadic. 

> ....the bidding time can be adjusted by the user in the next version.

That's great!  I really think that's all the issue is here.  I routinely watch as bids happen and they are very often hitting at the 1 second mark, which seems unnecessarily aggressive....  5 to 7 seconds should be more than ample.

> It will still take me a while to release the new version though (hopefully in October).

I look forward to it.  Thanks for your work!  If there's anything I can contribute (more docs?) please ask, I'd love to assist.  If you need an alpha / beta tester I can do that as well ;)

**Comment by sweitzel** [comment]
@dvanco I would have a test version ready. Actually I plan to release it on Saturday 2020-10-03.

Here is the chrome/edge version. You can extract the zip to a folder and instruct chrome to load a unpacked extension from it. You wont have access to your data from stable extension though, but you can export/import it with the "Storage Explorer" plugin. You should have another browser profile, to prevent messing with your "production" data :)

[bom-be_0.5.0_20201001_1827.zip](https://github.com/sweitzel/Biet-O-Matic-BE/files/5313493/bom-be_0.5.0_20201001_1827.zip)

**Comment by sweitzel** [comment]
Version 0.5.0 is fixing this issue by rewritten bidding procedure, as well as providing users the possibility to adjust the bid time.

**Comment by dvanco** [comment]
lol - wow - I just lost dozens of bids

**Comment by dvanco** [comment]
lol - this extension is TOTALLY hosed - all it does it open DOZENS of tabs
- it never bids

**Comment by dvanco** [comment]
every auction

[image: image.png]

**Comment by sweitzel** [comment]
@dvanco could you please take a bit of time and try to describe the error? Currently I have no clue what has was the issue. The image upload didn't work seemingly.

I tested bidding briefly with ebay.com / english language and it generally works. Therefore I need some support from you to find out what was the issue.

Please:
- create new GitHub issue for this new problem
- provide the item log for 1 or 2 failed items
- send console log (please send via mail to me for privacy reasons)
