### ISSUE TITLE
Adding ebay.ca

### ISSUE THREAD

**Issue by mikhoul** [sweitzel/Biet-O-Matic-BE#22]
Could you add ebay .ca please ?

Regards :octocat:

**Comment by sweitzel** [comment]
From the beginning I have designed BE to be limited to few regions. In a browser extension you need to whitelist each ebay site specifically (or whitelist all pages which is not so good). Also the efforts are higher.

Given that there are less than 2% international BE users, I think this does not make rationally sense.
You should be able to use ebay.com instead to manage your purchases.

**Comment by mikhoul** [comment]
> In a browser extension you need to whitelist each ebay site specifically


Not a lot of efforts it  take 2 seconds:...


It sure you will not have lot of international users  if you are not open to internationalize your extension, since currency are not the same on each ebay site it's not practical for me to use ebay.com to manage my auctions.

Regards :octocat: 

```
  "content_scripts": [
    {
      "matches": [
        "https://offer.ebay.com/*",
        "https://offer.ebay.ca/*",
        "https://offer.ebay.de/*"
      ],
      "js": ["contentScript_offer.bundle.js"]
    }
  ],
  "permissions": [
    "https://*.ebay.com/*",
    "https://offer.ebay.ca/*",
    "https://*.ebay.de/*",
    "activeTab",
    "storage",
    "power"
  ],

**Comment by sweitzel** [comment]
Regarding your statement:

> It sure you will not have lot of international users if you are not open to internationalize your extension

BE fully supports english and german language. It als supports ebay.com (US market) and there are less than 1% of users from this region. Therefore, from my perspective adding further support for other contries does not make sense economically.

Also personally I can not support this in a good way. Each additional site needs to be consequently supported, including the test efforts before each release.

**Comment by sweitzel** [comment]
Closing this issue for now:

- I will not add further international ebay platforms to the BE
- Feel free to contribute to this project via PR.
  - However it should be including "maintainer support" to ensure with each release each ebay platforms is tested.
