### ISSUE TITLE
Request: Button to add auction manually by URL.

### ISSUE THREAD

**Issue by mikhoul** [sweitzel/Biet-O-Matic-BE#23]
Right now I tried to ad an auction but since the auction format was not standard the BOM button did not appears on the auction page so I was not able to put the auction in BOM.

No button screenshot: 
![image](https://user-images.githubusercontent.com/5678673/101422705-57578b80-38c5-11eb-831b-8a74d1a1a2b2.png)

I had to put the auction on my watchlist which I did not want to do since it make other buyer aware and make the price rise....

So I'd like to just copy and paste the URL in BOM to add my auctions.

Regards :octocat:

**Comment by sweitzel** [comment]
While it seems reasonable to add items by copy&paste - I would also like to understand why the item wasn't processed by BE.
By the screenshot it looks like a regular item and should be processed by BE.

Do you have more information? Can you provide an item number which shows this symptom?

**Comment by mikhoul** [comment]
> - I would also like to understand why the item wasn't processed by BE.
> By the screenshot it looks like a regular item and should be processed by BE.
> 
> Do you have more information? Can you provide an item number which shows this symptom?

I'm pretty sure it's because the "unusual" auction format (auctions were offers are accepted), so the CSS/HTML is not the same as regular auctions.

Here's one: https://www.ebay.com/itm/AMD-Ryzen-7-2700X-3-7-GHz-8-Core-Desktop-Processor-Socket-AM4/313290619229

![image](https://user-images.githubusercontent.com/5678673/101968664-42913580-3bee-11eb-9629-406638cfe7db.png)


Regards :octocat:

**Comment by sweitzel** [comment]
Hmm so the request is not just to add items by copy/paste. Currently BE does not support "buy it now" items, including those with  "make offer" option.

Because basically the idea of BE is to make automated bidding. But for those items it does not bring a huge benefit of having it automated.

So basically you only want to include it in the BE overview table?

**Comment by mikhoul** [comment]
No, I just gave you the link in my previous message so you will have the CSS of the make an offer button.

It's a type of auction where you can make an offer to the seller before someone entered the first bid, so you have the "Place Bid" button **AND** the Make Offer button at the same time on the listing.

The Make Offer button disappear after the first bid.

More information here: https://tamebay.com/2017/10/new-make-offer-feature-launches-ebay-auctions.html

![image](https://user-images.githubusercontent.com/5678673/101991635-1c19db80-3c7c-11eb-9799-c992671f3615.png)


Regards :octocat:

**Comment by mikhoul** [comment]
Here's a link with the 2 buttons: https://www.ebay.com/itm/AMD-Ryzen-2nd-Gen-7-2700X-4-3-GHz-Eight-Core-YD270XBGM88AF-Processor/353317202479?

If there is no bid you will see the 2 buttons (Place Bid + Make Offer).

Regards :octocat:

**Comment by sweitzel** [comment]
Strange, for me the item works as intended with BE.
Can you please check the browser console of the tab - there is probably some error indicated which I need to be able to investigate this issue further. Or the HTML code is really different when you open the page from the US.

![image](https://user-images.githubusercontent.com/1214038/101993992-2d380c00-3cbf-11eb-8da6-7dfa677fd02c.png)

**Comment by mikhoul** [comment]
I don't see any error related to your extension 🤔

![image](https://user-images.githubusercontent.com/5678673/101995076-52b02000-3c95-11eb-8cb0-f420d470208c.png)

**Comment by sweitzel** [comment]
In version 0.5.4 its now possible to add items via paste (ctrl + v). 
One or more item numbers can be pasted and thus added to BE.

Anyhow, that the item was not added to BE is caused by some eBay Javascript "hang" issue and unrelated to BE functions.
