### ISSUE TITLE
Error while adding items from the eBay Watchlist: e is undefined

### ISSUE THREAD

**Issue by stuboy333** [sweitzel/Biet-O-Matic-BE#25]
This is weird, cant see any reason this item would be in OTHER category, what ever that is? You can see from the pic it was not possible to bid on it as no boxes on the right hand side. It was a normal auction.

![no right had side to bid on item](https://user-images.githubusercontent.com/77644747/104969988-ec2fc780-59e1-11eb-8681-9e3295659bff.jpg)
![other auctions](https://user-images.githubusercontent.com/77644747/104969990-ecc85e00-59e1-11eb-825f-c49b91361c23.jpg)

hope that is useful
Cheers
Stuboy

**Comment by sweitzel** [comment]
- Browser?
- BE version?

There are information missing for the item - so the parsing failed at a certain point. There is an unhandled exception happening.
Please check console log for any warning/error while parsing the auction and post it here please.

Update: I could reproduce it in Firefox with latest version. I get `e is undefined` error. Please include such information next time.
Already working on the fix.

**Comment by stuboy333** [comment]
Firefox
0.56 
Ah ok thanks, how do i get to console log please?
Cheers
Stu

**Comment by sweitzel** [comment]
As I was able to reproduce this, there is no need for the log anymore.
For the next time, the browser console log is reachable via F12, and then can be exported to a file with right mouse click typically.

**Comment by sweitzel** [comment]
Fixed with v0.5.7
