### ISSUE TITLE
Feature request: Shoop

### ISSUE THREAD

**Issue by Markus-Go** [sweitzel/Biet-O-Matic-BE#8]
Would it be possible to include Shoop Cashback Tracking somehow before a bid is placed? There is also a Shoop addon for Chrome/Firefox, maybe it can be invoked somehow?

**Comment by sweitzel** [comment]
Interesting, I was not aware of this. I currently have no idea how this could be technically done. I doubt I will find the time to work on this request - and also I would like to keep the Browser Extension as small as possible. If there was a huge demand for this, of course that would be an easier choice...

**Comment by schwabeltier** [comment]
Bei mir auch:
Ich würde gerne über elitebonus weitergeleitet werden.
**Es müsste vorher nur einmal ein Ref-Link aufgerufen werden.**
Danach öffnet sich die Startseite (.de), dann müsste nur der Artikel aufgerufen werden.
ebay.de/itm/artikelnummer. 
Das wäre alles. Es wäre mir min. 50EUR Wert, wenn das umgesetzt werden kann.
So können alle von Cashback profitieren.

**Comment by sweitzel** [comment]
Do you have examples for such URL or can explain the technical implementation?

**Comment by schwabeltier** [comment]
Yes, of course:
just this link:
https://www.elitebonus.de/shop-out/User-ID/ebay.html
The User-Id must be filled with a small integer of 5 chars.
Thats all. The link must be opened before opening ebay.de.
The link of elitebonus, like the shoop-link too refers to ebay.de/utm?/source=blabla&action=cashback&campaign=elitebonzen_de
After this the article can be opened.
Normaly the link must be opened once a session only. But in often cases in just works by opening the file every time.
I asked shoop for technical information. They use same technical solution.
So it might be good, to just implement a Cashback-Option, where user can type in the link, that should be opened before bidding.
Or maybe all 2hours, depence on personal cookie-setting of the use rand that stuff. So they need to recognize the purchase of the user. In my case of using elitebonus it should be ok to do so all few hours.
So the implementation might be just a textfield with fillout option and the task to open this link and then just open the ebay-articel-tab. In case of elitebonus the tab can be closed automatically, after reaching ebay.de. The elitbonus-tab loads in 5sec.  to reach ebay.de. Maybe you could implement the stuff - loading cashbacklink and ebay-article- in the same tab. This solution works 100% for shoop, elitebonus and others.
Regards

**Comment by sweitzel** [comment]
Currently no plan to implement this myself. Willing to accept PRs.
